name: Publish Nilaa Player

on:
    workflow_dispatch: # Manual trigger
    push:
        tags:
            - "v*" # Trigger on version tags

jobs:
    publish:
        strategy:
            matrix:
                os:
                    - { name: "linux", image: "ubuntu-latest" }
                    - { name: "windows", image: "windows-latest" }
                    - { name: "macos", image: "macos-latest" }

        runs-on: ${{ matrix.os.image }}

        steps:
            - name: GitHub checkout
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Get pnpm store directory
              id: pnpm-cache-dir
              shell: bash
              run: |
                  echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Generate icons (macOS)
              if: matrix.os.name == 'macos'
              run: pnpm run generate-icons-macos

            - name: Generate icons (Windows/Linux)
              if: matrix.os.name != 'macos'
              run: pnpm run generate-icons

            - name: Install native dependencies (Linux)
              if: matrix.os.name == 'linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss-dev libasound2-dev libgtk-3-dev libxshmfence-dev

            - name: Publish app
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm run publish
